name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  JAVA_VERSION: 25

jobs:
  build:
    name: 🔨 Compile
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            system: linux
            runner: ubuntu-latest
          - arch: arm64
            system: linux
            runner: ubuntu-24.04-arm
          - arch: amd64
            system: macos
            runner: macos-latest-large
          - arch: arm64
            system: macos
            runner: macos-26
    env:
      BUILD_IMAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.system }}-${{ matrix.arch }}
      BUILD_VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: graalvm-community
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build binary
        run: ./gradlew nativeCompile --no-daemon

      - name: Upload binary
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.BUILD_IMAGE_NAME }}
          path: build/native/nativeCompile/*

  container-build:
    name: 🐳 Build Container Image
    runs-on: ${{ matrix.runner }}
    needs:
      - build
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    env:
      BUILD_IMAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.system }}-${{ matrix.arch }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v8
        with:
          name: ${{ env.BUILD_IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},suffix=-${{ matrix.arch }}
            type=edge,suffix=-${{ matrix.arch }}
          labels: |
            org.opencontainers.image.title="traefik-configuration-provider"
            org.opencontainers.image.description="Dynamically expose Traefik routers to upstream Traefik instances"

      - name: Build and push
        uses: docker/build-push-action@v7
        id: build
        with:
          tags: ${{ env.REGISTRY }}/${{ github.repository }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          context: .
          platforms: linux/${{ matrix.arch }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: container-image-digests-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  container-merge:
    name: 📦 Merge Container Manifests
    runs-on: ubuntu-latest
    needs:
      - container-build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests
          pattern: container-image-digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ github.repository }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.meta.outputs.version }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v7
        id: artifacts
        with:
          merge-multiple: true
          pattern: "${{ github.event.repository.name }}-*"
          path: binaries

      - uses: sean0x42/markdown-extract@v2
        id: extract-changelog
        with:
          file: CHANGELOG.md
          pattern: ${{ github.ref_name }}
          no-print-matched-heading: true

      - uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          body: |
            ## Changelog
            ${{ steps.extract-changelog.outputs.markdown }}
          files: |
            ${{ steps.artifacts.outputs.download-path }}/*
